// API Configuration - Generated by Docker entrypoint or manually edited
// This file is loaded before app.js
const API_CONFIG = {
    // Use window.location.hostname for same-host deployments
    // Or set a specific host/IP for different setups
    host: window.location.hostname,
    
    // Backend API port - change this if you mapped the backend to a different port
    port: 8000,
    
    // Protocol (http/https)
    protocol: 'http'
};

// Build the API base URL
const API_BASE = `${API_CONFIG.protocol}://${API_CONFIG.host}:${API_CONFIG.port}`;
