#!/bin/sh
# Frontend entrypoint - configures API dynamically

# Configuration options:
# API_URL: Full URL to backend (e.g., https://ohsbackend.doanet.de)
#          If set, this overrides API_HOST and API_PORT
# API_HOST: Backend hostname (default: window.location.hostname)
# API_PORT: Backend port (default: 8000)
# API_PROTOCOL: http or https (default: http)

if [ -n "$API_URL" ]; then
    # Use full URL if provided (for reverse proxy setups)
    cat > /usr/share/nginx/html/api-config.js << EOF
// API Configuration - Generated by Docker entrypoint
const API_BASE = "${API_URL}";
console.log("API configured via API_URL:", API_BASE);
EOF
    echo "API configured: ${API_URL}"
else
    # Use host + port (for local/direct setups)
    API_PORT=${API_PORT:-8000}
    API_PROTOCOL=${API_PROTOCOL:-http}
    
    if [ -n "$API_HOST" ]; then
        HOST_VALUE="\"$API_HOST\""
    else
        HOST_VALUE="window.location.hostname"
    fi
    
    cat > /usr/share/nginx/html/api-config.js << EOF
// API Configuration - Generated by Docker entrypoint
const API_CONFIG = {
    host: ${HOST_VALUE},
    port: ${API_PORT},
    protocol: '${API_PROTOCOL}'
};
const API_BASE = \`\${API_CONFIG.protocol}://\${API_CONFIG.host}:\${API_CONFIG.port}\`;
console.log("API configured via host/port:", API_BASE);
EOF
    echo "API configured: ${API_PROTOCOL}://${API_HOST:-window.location.hostname}:${API_PORT}"
fi

# Start nginx
exec "$@"
