#!/bin/sh
# Frontend entrypoint - configures API port dynamically

# Get API port from environment or use default
API_PORT=${API_PORT:-8000}
API_HOST=${API_HOST:-$HOSTNAME}

# If API_HOST is not set, use window.location.hostname (empty string in config)
if [ -z "$API_HOST" ] || [ "$API_HOST" = "" ]; then
    HOST_VALUE="window.location.hostname"
else
    HOST_VALUE="\"$API_HOST\""
fi

# Update api-config.js with the correct port
cat > /usr/share/nginx/html/api-config.js << EOF
// API Configuration - Generated by Docker entrypoint
// This file is loaded before app.js
const API_CONFIG = {
    // Backend API host
    host: ${HOST_VALUE},
    
    // Backend API port
    port: ${API_PORT},
    
    // Protocol (http/https)
    protocol: 'http'
};

// Build the API base URL
const API_BASE = \`\${API_CONFIG.protocol}://\${API_CONFIG.host}:\${API_CONFIG.port}\`;
EOF

echo "API configured: http://${API_HOST:-window.location.hostname}:${API_PORT}"

# Start nginx
exec "$@"
